### ISSUE TITLE
`kubectl logs` fails for pods on kilo nodes behind NAT

### ISSUE THREAD

**Issue by brianthelion** [squat/kilo#272]
No errors on pod deployment; pods report READY and are, indeed, running when inspected directly on the node. `wg kilo0` is up and working correctly.

The issue only seems to affect `kubectl logs` and `kubectl exec`.

Node and Master operating system are both Ubuntu 21.10. Kubernetes distro is `kubeadm` with `flannel`. Master has a public IP, Node does not due to being behind NAT.

```
kubectl apply -f https://raw.githubusercontent.com/squat/kilo/main/manifests/crds.yaml
kubectl apply -f https://raw.githubusercontent.com/squat/kilo/main/manifests/kilo-kubeadm-flannel.yaml
```

Annotations applied to Nodes:

```
kilo.squat.ai/location=${LOCATION}
kilo.squat.ai/persistent-keepalive=5
```

Annotations applied to Master:

```
kilo.squat.ai/location=master
kilo.squat.ai/force-endpoint=${PUBLIC_IP}:51820
```

And finally, `kubectl logs {pod}` and `kubectl exec` both report:

```
Error from server: Get "https://192.168.1.26:10250/containerLogs/default/{pod}": dial tcp 192.168.1.26:10250: i/o timeout
```
where `192.168.1.26` is the IP provided by the router, not the one provided by `kilo`.

Maybe some more configuration is needed?

**Comment by brianthelion** [comment]
One additional tidbit: I'm allocating and annotating the Node objects by hand _before_ the kubelet joins the control plane (as opposed to letting the control plane do it automatically at `join` time).

**Comment by leonnicolas** [comment]
Can you ping pods on the nodes behind NAT from another location in the cluster? Aka is the pod network working?

**Comment by brianthelion** [comment]
@leonnicolas To test, I set up your `adjacency` service on a NodePort as follows:

```
kind: DaemonSet
apiVersion: apps/v1
metadata: 
  name: adjacency
  labels:
    app.kubernetes.io/name: adjacency
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adjacency
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adjacency
    spec:
      containers:
      - name: adjacency
        image: kiloio/adjacency
        args: 
        - --listen-address=:8080
        - --srv=_http._tcp.adjacency
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          failureThreshold: 2
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /ping
            port: http
          failureThreshold: 2
          periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: adjacency
  labels:
    app.kubernetes.io/name: adjacency
spec: 
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
    nodePort: 30163
  selector:
    app.kubernetes.io/name: adjacency
#  clusterIP: None

```

`curl ${PUBLIC_IP}:30163?format=json` times out. This is presumably due to the timeout on the pods themselves, so I checked the `adjacency` pod logs:

```
$ kubectl get pods
NAME               READY   STATUS    RESTARTS   AGE
adjacency-2bqx2    1/1     Running   0          46s
adjacency-9cccf    1/1     Running   0          46s

$ kubectl logs adjacency-9cccf
2022/02/11 15:02:49 using timeout 10s, using probe timeout 2s
2022/02/11 15:02:49 listening on :8080

$ kubectl logs adjacency-2bqx2
Error from server: Get "https://192.168.1.26:10250/containerLogs/default/adjacency-2bqx2/adjacency": dial tcp 192.168.1.26:10250: i/o timeout
```
