### ISSUE TITLE
Connection to K8S Service - SourceIP is not preserved (Source NAT)

### ISSUE THREAD

**Issue by ch9hn** [squat/kilo#330]
Hello together,
we are using a managed K8S cluster with the following Kilo image:
`docker.io/squat/kilo:bcb722b0b90271a6643d6360e69e702d578d6a06`

What we have done so far:
Added a Kilo peer via the following manifest:

```
apiVersion: kilo.squat.ai/v1alpha1
kind: Peer
metadata:
  name: gw-peer
spec:
  allowedIPs:
    - 10.4.0.99/32
    - 192.168.0.0/24 # Test Client Network
  publicKey: <PUBKEY>
  persistentKeepalive: 10
```

On the side of the VPN peer we have the following config, which was generated by kgctl:

```
[Interface]
Address = 10.4.0.99/24
SaveConfig = true
PrivateKey = <PRIVATEKEY>

[Peer]
PublicKey = <PUBKEY>
AllowedIPs = 100.64.2.0/24, 10.4.0.1/32
Endpoint = <IP>:51820
PersistentKeepalive = 10

[Peer]
PublicKey = <PUBKEY>
AllowedIPs = 100.64.4.0/24, 10.4.0.2/32, 10.32.0.0/12 # Service CIDR is added here.
Endpoint = <IP>:51820
PersistentKeepalive = 10

[Peer]
PublicKey = <PUBKEY>
AllowedIPs = 100.64.3.0/24, 10.4.0.3/32
Endpoint = <IP>:51820
PersistentKeepalive = 10

[Peer]
PublicKey = <PUBKEY>
AllowedIPs = 100.64.1.0/24, 10.4.0.4/32
Endpoint = <IP>:51820
PersistentKeepalive = 10
```

Now to the issue:

When we are sending UDP packets to our pod, the client IP needs to be preserved.
This is no problem, when we are sending on one Pod IP like 100.64.4.4.

But when we are sending the UDP packets to a K8S Service like this:

```
apiVersion: v1
kind: Service
metadata:
  name: svc-connector
  namespace: <MYSPACE>
spec:
  type: ClusterIP
  clusterIP: 10.40.40.40 # We set the clusterIP field, to identify and hardcode the IP.
  ports:
    - name: connector-udp
      protocol: UDP
      port: 5684
      targetPort: 5684
  selector:
    app: <MYAPP>
    component: test-connector
```
    
Then the Source IP is not preserved and we are seeing the IP address of the node.
    
```
UDP server message sent to 100.64.4.1:59778
processed data for xxxxx from 100.64.4.1`
```     
     
We need to preserve the source IP.
     
How we can do this?
Which options we need to switch on ?
